Dropdown
lekowan/love-words pull request #27
Opened 2024-10-28 22:12 UTC by lekowan

Created a dropdown menu using Radix. The dropdown menu pulls data from a language-list.json.

2024-10-28 23:43 UTC, seanmturley requested changes
It looks like this is working well.

I suggested a few small changes to make some things clearer or simpler, and to get rid of some console logging and errors.

I've pointed out the potential for some bigger refinements to be made, but maybe we look into those afterwards.

2024-10-28 23:43 UTC, seanmturley commented on src/data/language/language.ts
I think `getLanguageList` could be simpler:

```
export const getLanguageList = async () => {
  try {
    return await import(`@data/language-list.json`)
  } catch (_error) {
    throw new Error(`Failed to load language list`)
  }
}
```

2024-10-28 23:43 UTC, seanmturley commented on src/components/dropdown/dropdown.tsx
> +export const Dropdown = ({ languageList }: { languageList: LanguageList }) => {
I'm suspicious of the prop drilling required to get `languageList` here. It's passed down through 4 levels: 

`/[language]/page.tsx` > `StoryListTemplate` > `Header` > `Dropdown`

None of the levels above `Dropdown` actually use the data.

Do you want to go with it for now, and see if we can refine it later?

2024-10-28 23:43 UTC, seanmturley commented on src/components/dropdown/dropdown.tsx
> +            key="language"
The `key` of each child element needs to be unique (there are console errors in the browser). I think you probably meant for this to be:
```
key={language}
```

2024-10-28 23:43 UTC, seanmturley commented on src/components/dropdown/dropdown.tsx
> +    const newPath = pathname.replace(/\/(fr|jp)(\/|$)/, `/${language}/`)
Is the goal of this just to navigate between `/fr` and `/jp` and vice versa?

It works, so do you want to go with it for now? We could simplify it later.

2024-10-29 00:38 UTC, lekowan commented on src/app/[language]/page.tsx
> +  console.log(Object.keys(languageList))
Yep. Done.

2024-10-29 00:38 UTC, lekowan commented on src/components/header/header.tsx
> +import { LanguageList } from "@data/language/language"
Good catch

2024-10-29 00:41 UTC, lekowan commented on src/components/dropdown/dropdown.tsx
> +export const Dropdown = ({ languageList }: { languageList: LanguageList }) => {
Yes. Let's make a note of it. I had started to put it in a zustand store but couldn't get it to work (I was on the train then so not the best environment) so went with the easy option. I will make a ticket for refactoring this, feel free to pick it up.

2024-10-29 00:54 UTC, lekowan commented on src/components/dropdown/dropdown.tsx
> +            key="language"
Yes typo

2024-10-29 00:55 UTC, lekowan commented on src/components/dropdown/dropdown.tsx
> +    const newPath = pathname.replace(/\/(fr|jp)(\/|$)/, `/${language}/`)
That's right. This replace isn't pretty. Yes, let's find something more elegant later

2024-10-29 00:56 UTC, lekowan commented on src/components/dropdown/dropdown.tsx
> +import { LanguageList } from "@data/language"
Good point

2024-10-29 08:19 UTC, seanmturley approved these changes

2024-10-29 08:25 UTC, merged